#!/bin/bash

# Configure FreeRADIUS for MAB with VLAN support

echo "[*] Configuring FreeRADIUS for MAB..."

# Step 1: Create the mab_users file location
echo "[*] Creating mab_users file..."
sudo tee /etc/freeradius/3.0/mab_users > /dev/null << 'EOF'
# MAB Users - Auto-generated by FNAC
# Format: MAC-Address Cleartext-Password := "password"
#         [Tunnel-Type = VLAN,]
#         [Tunnel-Medium-Type = IEEE-802,]
#         [Tunnel-Private-Group-ID = "vlan_id"]

# Example entry (will be replaced by FNAC)
00:11:22:33:44:55 Cleartext-Password := "mab"
    Tunnel-Type = VLAN,
    Tunnel-Medium-Type = IEEE-802,
    Tunnel-Private-Group-ID = "100"
EOF

# Step 2: Update the default site config to use mab_users
echo "[*] Updating FreeRADIUS default site configuration..."
sudo tee /etc/freeradius/3.0/sites-enabled/default > /dev/null << 'EOF'
server default {
	listen {
		type = auth
		ipaddr = *
		port = 1812
		proto = udp
	}

	listen {
		type = acct
		ipaddr = *
		port = 1813
		proto = udp
	}

	authorize {
		preprocess
		files
	}

	authenticate {
		Auth-Type PAP {
			pap
		}
	}

	accounting {
		detail
		unix
	}

	session {
	}

	post-auth {
		Post-Auth-Type REJECT {
			attr_filter.access_reject
		}
	}

	pre-proxy {
	}

	post-proxy {
	}
}
EOF

# Step 3: Ensure files module is configured to use mab_users
echo "[*] Configuring files module..."
sudo tee /etc/freeradius/3.0/mods-enabled/files > /dev/null << 'EOF'
files {
	usersfile = ${confdir}/mab_users
	acctusersfile = ${confdir}/acct_users
	compat = 3.0
}
EOF

# Step 4: Validate and restart
echo "[*] Validating FreeRADIUS configuration..."
sudo freeradius -C -d /etc/freeradius/3.0

if [ $? -eq 0 ]; then
	echo "[+] Configuration is valid!"
	echo "[*] Restarting FreeRADIUS..."
	sudo systemctl restart freeradius
	
	sleep 2
	
	if sudo systemctl is-active --quiet freeradius; then
		echo "[+] FreeRADIUS is running!"
		echo "[+] Listening on:"
		sudo netstat -tulpn | grep freeradius
	else
		echo "[-] FreeRADIUS failed to start"
		sudo systemctl status freeradius
	fi
else
	echo "[-] Configuration validation failed!"
	exit 1
fi
