"""
FreeRADIUS Configuration Generator

Generates FreeRADIUS config files from FNAC device, client, and policy data.
Handles:
- clients.conf (RADIUS clients/devices)
- mab_users (MAC authentication bypass users)
- Configuration reloading
"""

import os
import subprocess
import logging
from typing import List, Optional
from pathlib import Path

from src.device_manager import Device_Manager
from src.client_manager import Client_Manager
from src.policy_engine import Policy_Engine
from src.models import PolicyDecision

logger = logging.getLogger(__name__)

# FreeRADIUS configuration paths
FREERADIUS_CONFIG_DIR = "/etc/freeradius/3.0"
FREERADIUS_CLIENTS_CONF = os.path.join(FREERADIUS_CONFIG_DIR, "clients.conf")
FREERADIUS_MAB_USERS = os.path.join(FREERADIUS_CONFIG_DIR, "mab_users")

# Backup directory for generated configs
BACKUP_DIR = "./freeradius_config_backup"


class FreeRADIUSConfigGenerator:
    """Generates and manages FreeRADIUS configuration files."""

    def __init__(
        self,
        device_manager: Device_Manager,
        client_manager: Client_Manager,
        policy_engine: Policy_Engine,
        config_dir: str = FREERADIUS_CONFIG_DIR,
    ):
        self.device_manager = device_manager
        self.client_manager = client_manager
        self.policy_engine = policy_engine
        self.config_dir = config_dir
        self._ensure_backup_dir()
        self._setup_freeradius_mab_config()

    def _ensure_backup_dir(self) -> None:
        """Ensure backup directory exists."""
        Path(BACKUP_DIR).mkdir(exist_ok=True)

    def _setup_freeradius_mab_config(self) -> None:
        """
        Setup FreeRADIUS to use mab_users file on initialization.
        This ensures FreeRADIUS is configured for MAB even if it was already running.
        """
        try:
            # Update the files module to use mab_users
            files_mod_path = os.path.join(self.config_dir, "mods-enabled", "files")
            files_mod_content = """files {
\tusersfile = ${confdir}/mab_users
\tacctusersfile = ${confdir}/acct_users
\tcompat = 3.0
}
"""
            
            # Only write if it doesn't exist or is different
            if not os.path.exists(files_mod_path):
                with open(files_mod_path, "w") as f:
                    f.write(files_mod_content)
                logger.info(f"Created {files_mod_path}")
            
            # Create initial mab_users file if it doesn't exist
            mab_users_path = os.path.join(self.config_dir, "mab_users")
            if not os.path.exists(mab_users_path):
                initial_content = self.generate_mab_users()
                with open(mab_users_path, "w") as f:
                    f.write(initial_content)
                logger.info(f"Created initial {mab_users_path}")
                
        except PermissionError:
            logger.warning("Permission denied setting up FreeRADIUS MAB config. Run with sudo.")
        except Exception as e:
            logger.warning(f"Failed to setup FreeRADIUS MAB config: {e}")

    def generate_clients_conf(self) -> str:
        """
        Generate clients.conf content from device manager.

        Returns:
            String content of clients.conf
        """
        devices = self.device_manager.list_devices()
        
        lines = [
            "# Auto-generated by FNAC",
            "# DO NOT EDIT MANUALLY - changes will be overwritten",
            "# Edit devices in FNAC UI instead",
            "",
        ]

        for device in devices:
            lines.append(f"client {device.ip_address} {{")
            lines.append(f'    ipaddr = {device.ip_address}')
            lines.append(f'    secret = "{device.shared_secret}"')
            lines.append(f'    shortname = "{device.id}"')
            lines.append("    nastype = generic")
            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def generate_mab_users(self) -> str:
        """
        Generate mab_users file content from client and policy data.

        Returns:
            String content of mab_users file
        """
        clients = self.client_manager.list_clients()
        
        lines = [
            "# Auto-generated by FNAC",
            "# DO NOT EDIT MANUALLY - changes will be overwritten",
            "# Edit clients and policies in FNAC UI instead",
            "",
            "# MAB Users - MAC Authentication Bypass",
            "# Format: MAC-Address Cleartext-Password := \"password\"",
            "#         [Tunnel-Type = VLAN,]",
            "#         [Tunnel-Medium-Type = IEEE-802,]",
            "#         [Tunnel-Private-Group-ID = \"vlan_id\"]",
            "",
        ]

        for client in clients:
            mac = client.mac_address
            
            # Get policy for this client's group
            decision, vlan_id = self.policy_engine.evaluate_policy(
                client.client_group_id
            )

            # Build user entry
            lines.append(f'{mac} Cleartext-Password := "mab"')

            # Add VLAN attributes if policy specifies VLAN assignment
            if decision == PolicyDecision.ACCEPT_WITH_VLAN and vlan_id:
                lines.append("    Tunnel-Type = VLAN,")
                lines.append("    Tunnel-Medium-Type = IEEE-802,")
                lines.append(f'    Tunnel-Private-Group-ID = "{vlan_id}"')
            elif decision == PolicyDecision.REJECT:
                # Rejected clients still need an entry but won't authenticate
                lines.append("    # REJECTED - will not authenticate")

            lines.append("")

        return "\n".join(lines)

    def write_clients_conf(self, dry_run: bool = False) -> bool:
        """
        Write clients.conf to FreeRADIUS config directory.

        Args:
            dry_run: If True, don't actually write, just return success

        Returns:
            True if successful, False otherwise
        """
        try:
            content = self.generate_clients_conf()
            
            if dry_run:
                logger.info("DRY RUN: Would write clients.conf")
                logger.debug(f"Content:\n{content}")
                return True

            # Backup existing file
            self._backup_file(FREERADIUS_CLIENTS_CONF)

            # Write new file
            with open(FREERADIUS_CLIENTS_CONF, "w") as f:
                f.write(content)

            logger.info(f"Updated {FREERADIUS_CLIENTS_CONF}")
            return True

        except PermissionError:
            logger.error(f"Permission denied writing to {FREERADIUS_CLIENTS_CONF}")
            logger.error("Run with sudo or ensure proper permissions")
            return False
        except Exception as e:
            logger.error(f"Error writing clients.conf: {e}")
            return False

    def write_mab_users(self, dry_run: bool = False) -> bool:
        """
        Write mab_users file to FreeRADIUS config directory.

        Args:
            dry_run: If True, don't actually write, just return success

        Returns:
            True if successful, False otherwise
        """
        try:
            content = self.generate_mab_users()

            if dry_run:
                logger.info("DRY RUN: Would write mab_users")
                logger.debug(f"Content:\n{content}")
                return True

            # Backup existing file
            self._backup_file(FREERADIUS_MAB_USERS)

            # Write new file
            with open(FREERADIUS_MAB_USERS, "w") as f:
                f.write(content)

            logger.info(f"Updated {FREERADIUS_MAB_USERS}")
            return True

        except PermissionError:
            logger.error(f"Permission denied writing to {FREERADIUS_MAB_USERS}")
            logger.error("Run with sudo or ensure proper permissions")
            return False
        except Exception as e:
            logger.error(f"Error writing mab_users: {e}")
            return False

    def reload_freeradius(self) -> bool:
        """
        Reload FreeRADIUS configuration.
        Falls back to restart if reload is not supported.

        Returns:
            True if successful, False otherwise
        """
        try:
            # Try systemctl reload first
            result = subprocess.run(
                ["sudo", "systemctl", "reload", "freeradius"],
                capture_output=True,
                timeout=10,
            )

            if result.returncode == 0:
                logger.info("FreeRADIUS reloaded successfully")
                return True
            
            # If reload not supported, try restart
            stderr = result.stderr.decode() if result.stderr else ""
            if "reload is not applicable" in stderr or "not supported" in stderr:
                logger.info("Reload not supported, restarting FreeRADIUS instead")
                result = subprocess.run(
                    ["sudo", "systemctl", "restart", "freeradius"],
                    capture_output=True,
                    timeout=10,
                )
                if result.returncode == 0:
                    logger.info("FreeRADIUS restarted successfully")
                    return True
                else:
                    error_msg = result.stderr.decode() if result.stderr else "Unknown error"
                    logger.error(f"Failed to restart FreeRADIUS: {error_msg}")
                    return False
            else:
                logger.error(f"Failed to reload FreeRADIUS: {stderr}")
                return False

        except subprocess.TimeoutExpired:
            logger.error("FreeRADIUS reload/restart timed out")
            return False
        except Exception as e:
            logger.error(f"Error reloading FreeRADIUS: {e}")
            return False

    def update_all_configs(self, reload: bool = True, dry_run: bool = False) -> bool:
        """
        Update all FreeRADIUS configuration files.

        Args:
            reload: If True, reload FreeRADIUS after updating
            dry_run: If True, don't actually write files

        Returns:
            True if all updates successful, False otherwise
        """
        success = True

        # Update clients.conf
        if not self.write_clients_conf(dry_run=dry_run):
            success = False

        # Update mab_users
        if not self.write_mab_users(dry_run=dry_run):
            success = False

        # Reload FreeRADIUS if requested and not dry run
        if success and reload and not dry_run:
            if not self.reload_freeradius():
                success = False

        return success

    def _backup_file(self, filepath: str) -> None:
        """
        Backup a file before overwriting.

        Args:
            filepath: Path to file to backup
        """
        if not os.path.exists(filepath):
            return

        try:
            filename = os.path.basename(filepath)
            backup_path = os.path.join(BACKUP_DIR, f"{filename}.bak")
            
            # Keep only last 5 backups
            import shutil
            if os.path.exists(backup_path):
                for i in range(4, 0, -1):
                    old = f"{backup_path}.{i}"
                    new = f"{backup_path}.{i+1}"
                    if os.path.exists(old):
                        os.rename(old, new)
                os.rename(backup_path, f"{backup_path}.1")

            shutil.copy2(filepath, backup_path)
            logger.debug(f"Backed up {filepath} to {backup_path}")

        except Exception as e:
            logger.warning(f"Failed to backup {filepath}: {e}")

    def validate_config(self) -> bool:
        """
        Validate FreeRADIUS configuration syntax.

        Returns:
            True if valid, False otherwise
        """
        try:
            result = subprocess.run(
                ["sudo", "freeradius", "-C"],
                capture_output=True,
                timeout=10,
            )

            if result.returncode == 0:
                logger.info("FreeRADIUS configuration is valid")
                return True
            else:
                logger.error(f"FreeRADIUS config validation failed: {result.stderr.decode()}")
                return False

        except subprocess.TimeoutExpired:
            logger.error("FreeRADIUS validation timed out")
            return False
        except Exception as e:
            logger.error(f"Error validating FreeRADIUS config: {e}")
            return False
